---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.04

suites:
  - name: default
    run_list:
      - recipe[chefdk_getting_started::default]
    attributes:
  - name: server
    run_list:
      - recipe[chefdk_getting_started::default]
    attributes:
